load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
load("@rules_cc//cc:repositories.bzl", "rules_cc_toolchains")
load("@rules_folly//bazel:folly_deps.bzl", "folly_deps")
load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")
load("@rules_fuzzing//fuzzing:repositories.bzl", "rules_fuzzing_dependencies")
load("@rules_pcl//bzl:init_deps.bzl", "pcl_init_deps")
load("@rules_pcl//bzl:repositories.bzl", "pcl_repositories")
load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
load("@rules_python//python:pip.bzl", "pip_parse")
load("@rules_python//python:repositories.bzl", "python_register_toolchains")
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
load("@rules_fuzzing//fuzzing:init.bzl", "rules_fuzzing_init")
load("//bazel:go_deps.bzl", "go_dependencies")
load("@rules_proto_grpc//grpc-gateway:repositories.bzl", rules_proto_grpc_gateway_repos = "gateway_repos")
load("@grpc_ecosystem_grpc_gateway//:repositories.bzl", grpc_ecosystem_grpc_gateway = "go_repositories")
load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_repos", "rules_proto_grpc_toolchains")

def bingo_init_deps():
    protobuf_deps()
    grpc_deps()
    rules_cc_toolchains()
    folly_deps()
    rules_foreign_cc_dependencies()
    rules_fuzzing_dependencies()
    pcl_init_deps()
    pcl_repositories()
    rules_pkg_dependencies()
    rules_proto_toolchains()
    pip_parse()
    python_register_toolchains()
    grpc_extra_deps()
    rules_fuzzing_init()
    go_dependencies()
    rules_proto_grpc_gateway_repos()
    grpc_ecosystem_grpc_gateway()
    rules_proto_grpc_toolchains()
    rules_proto_grpc_repos()
