cc_library(
    name = "command_base",
    srcs = ["command_base.cc"],
    hdrs = ["command_base.h"],
)

cc_binary(
    name = "command_main",
    srcs = ["command_main.cc"],
    deps = [
        "@com_github_google_glog//:glog",
    ],
)
